baseURL = "https://wizardfree.uk"
languageCode = "en-gb"
title = "WizardFree"
theme = "retromodern"
[params]
 author = "Joseph Fleet"
 description = "Personal website of a Junior IT Professional"
[permalinks]
 posts = ":slug/"
[taxonomies]
 tag = "tags"
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = false
      xhtml = false
  [markup.highlight]
   anchorLineNos = false
   codeFences = true
   guessSyntax = false
   hl_Lines = ''
   lineAnchors = ''
   lineNoStart = 1
   lineNos = true
   lineNumbersInTable = true
   noClasses = true
   style = 'colorful'
   tabWidth = 4
