baseURL = "wizardfree.uk"
languageCode = "en-gb"
title = "WizardFree"
theme = "retromodern"
[params]
 author = "Joseph Fleet"
 description = "Personal website of a Junior IT Professional"
 pygmentsUseClasses = true
[permalinks]
 posts = ":slug/"
[taxonomies]
 tag = "tags"
[markup.goldmark.renderer]
 unsafe= true
[markup]
[markup.highlight]
 anchorLineNos = false
 codeFences = true
 guessSyntax = false
 hl_Lines = ""
 lineAnchors = ""
 lineNoStart = 1
 lineNos = false
 lineNumbersInTable = true
 noClasses = true
 style = "perldoc"
 tabWidth = 4
