name = "sidebyside"
license = "GNU GPLv3"
licenselink = "https://choosealicense.com/licenses/gpl-3.0/"
description = ""
homepage = "http://wizardfree.uk/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "wizardfree"
  homepage = "wizardfree.uk"